---
openapi: "3.1"
info:
  description: "This is of the blueprints API."
  version: "2022-03-05T04:04:29Z"
  title: "Blueprints"
host: "lok608s285.execute-api.us-east-1.amazonaws.com"
basePath: "/staging"
schemes:
- "https"
paths:
  /blueprints:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        required: false
        type: "string"
      - name: "page"
        in: "query"
        required: false
        type: "string"
      responses:
        '200':
          description: 'All blueprints.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blueprints'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:blueprints-staging-blueprints-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.limit: "method.request.querystring.limit"
        requestTemplates:
          application/json: "{\n    \"page\" : \"$input.params('page')\",\n    \"\
            limit\" : \"$input.params('limit')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      consumes:
      - "application/json"
      requestBody:
        description: Blueprint
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Blueprint"
      responses:
        '201':
          description: 'Single Blueprint'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blueprint'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:blueprints-staging-blueprints-post/invocations"
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /blueprints/{blueprint_id}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "blueprint_id"
        in: "path"
        required: true
        type: "string"
      responses:
        '200':
          description: 'Single Blueprint'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blueprint'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:blueprints-staging-blueprints-blueprint_id-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.blueprint_id: "method.request.path.blueprint_id"
        requestTemplates:
          application/json: "{\n    \"blueprint_id\" : \"$input.params('blueprint_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    put:
      consumes:
      - "application/json"
      parameters:
      - name: "blueprint_id"
        in: "path"
        required: true
        type: "string"
      requestBody:
        description: Blueprint
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Blueprint"        
      responses:
        '204':
          description: 'All blueprints.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:blueprints-staging-blueprints-blueprint_id-put/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.blueprint_id: "method.request.path.blueprint_id"
        requestTemplates:
          application/json: "{\n    \"blueprint_id\" : \"$input.params('blueprint_id')\"\
            ,\n    \"body\" : $input.json('$') \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    delete:
      consumes:
      - "application/json"
      parameters:
      - name: "blueprint_id"
        in: "path"
        required: true
        type: "string"
      responses:
        '204':
          description: 'All blueprints.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:blueprints-staging-blueprints-blueprint_id-delete/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.blueprint_id: "method.request.path.blueprint_id"
        requestTemplates:
          application/json: "{\n    \"blueprint_id\" : \"$input.params('blueprint_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
components:
  schemas:
    Blueprints:
      type: array
      items:
        $ref: '#/components/schemas/Blueprint'      
    Blueprint:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        version:
          type: string          
        description:
          type: string
        collection_id:
          type: string
        state:
          type: string 
          description: The overall state of the completeness of blueprint.               
        maturity:
          type: string 
          description: The maturity of the blueprint (foundational, optimized, trasformational).              
        discussion:
          type: string 
          description: 'A link to the Github discussion for managing this blueprint.'
        yaml:
          type: string 
          description: 'A link to the raw YAMl for this blueprint.'