openapi: "3.0.0"
info:
  title: "Landscapes"
  description: "This is of the landscapes API."
  version: "2022-03-05T04:04:29Z"
servers:
- url: 
paths:
  /landscapes:
    get:
      summary: Get Landscapes
      description: Gets all landscapes.         
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: string        
      - name: "page"
        in: "query"
        required: false
        schema:
          type: string         
      responses:
        '200':
          description: 'All landscapes.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landscapes'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:landscapes-staging-landscapes-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.limit: "method.request.querystring.limit"
        requestTemplates:
          application/json: "{\n    \"page\" : \"$input.params('page')\",\n    \"\
            limit\" : \"$input.params('limit')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      summary: Add Landscape
      description: Adds a new landscape.    
      requestBody:
        description: Landscape
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Landscape"
      responses:
        '201':
          description: 'Single Landscape'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landscape'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:landscapes-staging-landscapes-post/invocations"
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /landscapes/{landscape_id}:
    get:
      parameters:
      - name: "landscape_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '200':
          description: 'Single Landscape'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landscape'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:landscapes-staging-landscapes-landscape_id-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.landscape_id: "method.request.path.landscape_id"
        requestTemplates:
          application/json: "{\n    \"landscape_id\" : \"$input.params('landscape_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    put:
      parameters:
      - name: "landscape_id"
        in: "path"
        required: true
        schema:
          type: string  
      requestBody:
        description: Landscape
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Landscape"        
      responses:
        '204':
          description: 'All landscapes.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:landscapes-staging-landscapes-landscape_id-put/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.landscape_id: "method.request.path.landscape_id"
        requestTemplates:
          application/json: "{\n    \"landscape_id\" : \"$input.params('landscape_id')\"\
            ,\n    \"body\" : $input.json('$') \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    delete:
      parameters:
      - name: "landscape_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '204':
          description: 'All landscapes.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:landscapes-staging-landscapes-landscape_id-delete/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.landscape_id: "method.request.path.landscape_id"
        requestTemplates:
          application/json: "{\n    \"landscape_id\" : \"$input.params('landscape_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: "x-api-key"
      in: header
  schemas:
    Landscapes:
      type: array
      items:
        $ref: '#/components/schemas/Landscape'      
    Landscape:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        version:
          type: string          
        description:
          type: string
        website:
          type: string
        api:
          type: string      
        workspace:
          type: string      
        rating:
          type: integer                                
security:
  - api_key: []              