openapi: "3.0.0"
info:
  title: "Links"
  description: "This is of the links API."
  version: "2022-03-05T04:04:29Z"
servers:
- url: 
paths:
  /links:
    get:
      summary: Get Links
      description: Gets all links.         
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: string        
      - name: "page"
        in: "query"
        required: false
        schema:
          type: string         
      responses:
        '200':
          description: 'All links.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Links'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:links-staging-links-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.limit: "method.request.querystring.limit"
        requestTemplates:
          application/json: "{\n    \"page\" : \"$input.params('page')\",\n    \"\
            limit\" : \"$input.params('limit')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      summary: Add Link
      description: Adds a new link.    
      requestBody:
        description: Link
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Link"
      responses:
        '201':
          description: 'Single Link'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:links-staging-links-post/invocations"
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /links/{link_id}:
    get:
      parameters:
      - name: "link_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '200':
          description: 'Single Link'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:links-staging-links-link_id-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.link_id: "method.request.path.link_id"
        requestTemplates:
          application/json: "{\n    \"link_id\" : \"$input.params('link_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    put:
      parameters:
      - name: "link_id"
        in: "path"
        required: true
        schema:
          type: string  
      requestBody:
        description: Link
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Link"        
      responses:
        '204':
          description: 'All links.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:links-staging-links-link_id-put/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.link_id: "method.request.path.link_id"
        requestTemplates:
          application/json: "{\n    \"link_id\" : \"$input.params('link_id')\"\
            ,\n    \"body\" : $input.json('$') \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    delete:
      parameters:
      - name: "link_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '204':
          description: 'All links.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:links-staging-links-link_id-delete/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.link_id: "method.request.path.link_id"
        requestTemplates:
          application/json: "{\n    \"link_id\" : \"$input.params('link_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: "x-api-key"
      in: header
  schemas:
    Links:
      type: array
      items:
        $ref: '#/components/schemas/Link'      
    Link:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        version:
          type: string          
        description:
          type: string
        url:
          type: string
security:
  - api_key: []              