openapi: "3.0.0"
info:
  title: "Roles"
  description: "This is of the roles API."
  version: "2022-03-05T04:04:29Z"
servers:
- url: 
paths:
  /roles:
    get:
      summary: Get Roles
      description: Gets all roles.         
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: string        
      - name: "page"
        in: "query"
        required: false
        schema:
          type: string         
      responses:
        '200':
          description: 'All roles.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roles'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:roles-staging-roles-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.limit: "method.request.querystring.limit"
        requestTemplates:
          application/json: "{\n    \"page\" : \"$input.params('page')\",\n    \"\
            limit\" : \"$input.params('limit')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      summary: Add Role
      description: Adds a new role.    
      requestBody:
        description: Role
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Role"
      responses:
        '201':
          description: 'Single Role'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:roles-staging-roles-post/invocations"
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /roles/{role_id}:
    get:
      parameters:
      - name: "role_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '200':
          description: 'Single Role'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:roles-staging-roles-role_id-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.role_id: "method.request.path.role_id"
        requestTemplates:
          application/json: "{\n    \"role_id\" : \"$input.params('role_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    put:
      parameters:
      - name: "role_id"
        in: "path"
        required: true
        schema:
          type: string  
      requestBody:
        description: Role
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Role"        
      responses:
        '204':
          description: 'All roles.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:roles-staging-roles-role_id-put/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.role_id: "method.request.path.role_id"
        requestTemplates:
          application/json: "{\n    \"role_id\" : \"$input.params('role_id')\"\
            ,\n    \"body\" : $input.json('$') \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    delete:
      parameters:
      - name: "role_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '204':
          description: 'All roles.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:roles-staging-roles-role_id-delete/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.role_id: "method.request.path.role_id"
        requestTemplates:
          application/json: "{\n    \"role_id\" : \"$input.params('role_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: "x-api-key"
      in: header
  schemas:
    Roles:
      type: array
      items:
        $ref: '#/components/schemas/Role'      
    Role:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        version:
          type: string          
        description:
          type: string
        collection_id:
          type: string
security:
  - api_key: []              