openapi: "3.0.0"
info:
  title: "Videos"
  description: "This is of the videos API."
  version: "2022-03-05T04:04:29Z"
servers:
- url: 
paths:
  /videos:
    get:
      summary: Get Videos
      description: Gets all videos.         
      parameters:
      - name: "limit"
        in: "query"
        required: false
        schema:
          type: string        
      - name: "page"
        in: "query"
        required: false
        schema:
          type: string         
      responses:
        '200':
          description: 'All videos.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Videos'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:videos-staging-videos-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.limit: "method.request.querystring.limit"
        requestTemplates:
          application/json: "{\n    \"page\" : \"$input.params('page')\",\n    \"\
            limit\" : \"$input.params('limit')\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    post:
      summary: Add Video
      description: Adds a new video.    
      requestBody:
        description: Video
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Video"
      responses:
        '201':
          description: 'Single Video'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:videos-staging-videos-post/invocations"
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /videos/{video_id}:
    get:
      parameters:
      - name: "video_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '200':
          description: 'Single Video'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:videos-staging-videos-video_id-get/invocations"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.video_id: "method.request.path.video_id"
        requestTemplates:
          application/json: "{\n    \"video_id\" : \"$input.params('video_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    put:
      parameters:
      - name: "video_id"
        in: "path"
        required: true
        schema:
          type: string  
      requestBody:
        description: Video
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Video"        
      responses:
        '204':
          description: 'All videos.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:videos-staging-videos-video_id-put/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.video_id: "method.request.path.video_id"
        requestTemplates:
          application/json: "{\n    \"video_id\" : \"$input.params('video_id')\"\
            ,\n    \"body\" : $input.json('$') \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    delete:
      parameters:
      - name: "video_id"
        in: "path"
        required: true
        schema:
          type: string  
      responses:
        '204':
          description: 'All videos.'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:007596076917:function:videos-staging-videos-video_id-delete/invocations"
        responses:
          default:
            statusCode: "204"
        requestParameters:
          integration.request.path.video_id: "method.request.path.video_id"
        requestTemplates:
          application/json: "{\n    \"video_id\" : \"$input.params('video_id')\"\
            \n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: "x-api-key"
      in: header
  schemas:
    Videos:
      type: array
      items:
        $ref: '#/components/schemas/Video'      
    Video:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        version:
          type: string          
        description:
          type: string
        collection_id:
          type: string
security:
  - api_key: []              