name: Deploy to Lambda
on: [push]
jobs:
  deploy_source:
    name: Deploy to Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
          
      # Blueprints
      - name: blueprints get lambda deploy zip
        uses: kinlane/blueprints@main   
        with:
          args: zip -qq -r blueprints-get.zip blueprints/get/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blueprints-staging-blueprints-get
          zip_file: blueprints-get.zip

      - name: blueprints post lambda deploy zip
        uses: kinlane/blueprints@main   
        with:
          args: zip -qq -r blueprints-post.zip blueprints/post/index.js node_modules
      - name: blueprints post lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blueprints-staging-blueprints-post
          zip_file: blueprints-post.zip

      - name: blueprints id get lambda deploy zip
        uses: kinlane/blueprints@main   
        with:
          args: zip -qq -r blueprints-id-get.zip blueprints/id/get/index.js node_modules
      - name: blueprints id get lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blueprints-staging-blueprints-blueprint_id-get
          zip_file: blueprints-id-get.zip       

      - name: blueprints id put lambda deploy zip
        uses: kinlane/blueprints@main   
        with:
          args: zip -qq -r blueprints-id-put.zip blueprints/id/put/index.js node_modules
      - name: blueprints id put lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blueprints-staging-blueprints-blueprint_id-put
          zip_file: blueprints-id-put.zip       

      - name: blueprints id delete lambda deploy zip
        uses: kinlane/blueprints@main   
        with:
          args: zip -qq -r blueprints-id-delete.zip blueprints/id/delete/index.js node_modules
      - name: blueprints id delete lambda deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: blueprints-staging-blueprints-blueprint_id-delete
          zip_file: blueprints-id-delete.zip                              

      ## Contract Testing
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 12959542-bbb207a0-3973-49ca-8b45-cc59969e4d03
          environment: 12959542-0d1a98dd-aced-429f-a3e0-5cb3113feef2

      ## Security Testing
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 12959542-acacd777-181e-45bc-93db-aa9acd334f9b
          environment: 12959542-0d1a98dd-aced-429f-a3e0-5cb3113feef2   

      ## Governance Design
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 12959542-cc59ef12-c1d5-408f-8d1f-4ac85aa1b8a3
          environment: 12959542-0d1a98dd-aced-429f-a3e0-5cb3113feef2                 